### ISSUE TITLE
Stop screen from going to sleep when using on a mobile device

### ISSUE THREAD

**Issue by bhopkinson** [jparkhouse/hanabi-tracker#10]
Stop screen from going to sleep when using on a mobile device

**Comment by jparkhouse** [comment]
This was potentially resolved in release 0.5.1 - further testing is needed, as support for the wakelock API varies by device/browser. To test:
- If the API is supported, the wake lock button appears in the buttons above the cards;
- It starts in the off state, but turning it on should change the button text and stop the device sleeping
- Tapping again should release the lock and allow the device to sleep

I'll leave this issue open for your testing results.

**Comment by bhopkinson** [comment]
This appeared to work well for me during the game today. I will close the issue - thanks!
