### ISSUE TITLE
Number disappearing when hint re-recorded 

### ISSUE THREAD

**Issue by TheoWakelin** [jparkhouse/hanabi-tracker#64]
When recording a hint,  cards can loose their numbers if a new card is re-hinted the same thing.

For example in a 3 card game:
I record a hint against card 1, saying it is a 5. 
I then discard card 2 
I then record a hint against the new card in position 3 saying its a 5.
The 5 on card 1 will disappear. 

Example image

![image](https://github.com/jparkhouse/hanabi-tracker/assets/118267098/70b39744-ae5e-48dd-a184-f3851e3b0c3a)

**Comment by jparkhouse** [comment]
Resolved :)
